/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./src/components/ui/ArticleCard.vue')['default']
    AthleteCard: typeof import('./src/components/ui/AthleteCard.vue')['default']
    AthleteModal: typeof import('./src/components/AthleteModal.vue')['default']
    AthleteRow: typeof import('./src/components/ui/AthleteRow.vue')['default']
    CommandPaletteModal: typeof import('./src/components/CommandPaletteModal.vue')['default']
    ErrorBoundary: typeof import('./src/components/ui/ErrorBoundary.vue')['default']
    EventModal: typeof import('./src/components/EventModal.vue')['default']
    EventRow: typeof import('./src/components/ui/EventRow.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FrappeToast: typeof import('./src/components/FrappeToast.vue')['default']
    HeroBanner: typeof import('./src/components/HeroBanner.vue')['default']
    MedalBadge: typeof import('./src/components/ui/MedalBadge.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/ui/SearchInput.vue')['default']
    SectionHeader: typeof import('./src/components/ui/SectionHeader.vue')['default']
    SegmentedControl: typeof import('./src/components/ui/SegmentedControl.vue')['default']
    TweakPanel: typeof import('./src/components/TweakPanel.vue')['default']
    WkfBadge: typeof import('./src/components/ui/WkfBadge.vue')['default']
  }
}
